# Generated by Django 4.2.1 on 2023-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15)),
                ('clave', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
