# Generated by Django 4.2.1 on 2023-07-23 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicioApp', '0002_asignatura_carrera_syllabus_unidad_tiporeferencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='id_usurio',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
