# Generated by Django 4.2.1 on 2023-07-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0004_informativo_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informativo',
            name='id_asignatura',
        ),
        migrations.RemoveField(
            model_name='informativo',
            name='id_carrera',
        ),
        migrations.RemoveField(
            model_name='informativo',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='informativo',
            name='id_ver_syllabus',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Informativo',
        ),
    ]
