# Generated by Django 4.2.1 on 2023-07-23 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicioApp', '0005_remove_informativo_id_asignatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id_informativo', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=20)),
                ('informacion', models.CharField(max_length=200)),
                ('asignatura', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=20)),
                ('prerrequisito', models.CharField(blank=True, max_length=50)),
                ('correquisito', models.CharField(blank=True, max_length=50)),
                ('unidad_organ', models.CharField(max_length=20)),
                ('horas_docencia', models.IntegerField()),
                ('horas_prac_docente', models.IntegerField()),
                ('horas_pract_autonoma', models.IntegerField()),
                ('horas_trab_autonomo', models.IntegerField()),
                ('objetivo_general', models.CharField(blank=True, max_length=50)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_ver_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.syllabus')),
            ],
        ),
    ]
