# Generated by Django 4.2.1 on 2023-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0006_informativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativo',
            name='profesional',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
