# Generated by Django 4.2.1 on 2023-07-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0007_informativo_profesional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemUnidad',
        ),
    ]
