# Generated by Django 4.2.1 on 2023-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0010_alter_aporteteorico_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporteteorico',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
    ]
