# Generated by Django 4.2.1 on 2023-07-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0011_alter_aporteteorico_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='informativo',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='informativo',
            name='id_asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.asignatura'),
        ),
    ]
