# Generated by Django 4.2.1 on 2023-07-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0013_aporteperfil_id_asignatura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo_especifico',
            fields=[
                ('id_objetivo_especifico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=500)),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.asignatura')),
                ('id_ver_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.syllabus')),
            ],
        ),
    ]
