# Generated by Django 4.2.1 on 2023-07-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0014_objetivo_especifico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemunidad',
            name='gestion_practica',
        ),
    ]
