# Generated by Django 4.2.1 on 2023-07-31 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0015_remove_itemunidad_gestion_practica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencia',
            old_name='titulo_obra',
            new_name='basica',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='id_tipo_referencia',
        ),
        migrations.AddField(
            model_name='referencia',
            name='complementaria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referencia',
            name='id_ver_syllabus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.syllabus'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='TipoReferencia',
        ),
    ]
