# Generated by Django 4.2.1 on 2023-07-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0017_remove_productoacademico_id_ver_syllabus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id_prod_academico', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=500)),
                ('objetivo', models.CharField(max_length=500)),
                ('productos_parciales', models.CharField(blank=True, max_length=500)),
                ('resultados', models.CharField(blank=True, max_length=500)),
                ('integracion', models.CharField(blank=True, max_length=500)),
                ('id_ver_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.syllabus')),
            ],
        ),
    ]
