# Generated by Django 4.2.1 on 2023-08-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0018_productoacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunidad',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
