# Generated by Django 4.2.1 on 2023-08-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0019_alter_itemunidad_contenido_alter_unidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoacademico',
            name='detalle',
        ),
        migrations.AlterField(
            model_name='ambienteaprendizaje',
            name='detalle',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='informativo',
            name='carrera',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='informativo',
            name='objetivo_general',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='integracion',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='objetivo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='productos_parciales',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='resultados',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='ProductoAcademicoItem',
            fields=[
                ('id_prod_academicoItem', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=1000)),
                ('id_ver_syllabus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.syllabus')),
            ],
        ),
    ]
