# Generated by Django 4.2.1 on 2023-08-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0020_remove_productoacademico_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente2',
            fields=[
                ('id_Profesores2', models.AutoField(primary_key=True, serialize=False)),
                ('nombreJefe', models.CharField(max_length=100)),
                ('nombreCoordinador', models.CharField(max_length=100)),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_Profesores', models.AutoField(primary_key=True, serialize=False)),
                ('docente_nombre', models.CharField(max_length=1000)),
                ('firma', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField()),
                ('id_asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicioApp.asignatura')),
            ],
        ),
    ]
